MethodsDemo m1 = new MethodsDemo();
//m1.newMessage('Alija');

m1.returnMessage('Jenny');//method works, not assigned

MethodsDemo m2 = new MethodsDemo();
//returnMessage is retutning a string
    //so, we are assignemtn to a string variable called r1
string r1 = m2.returnMessage('Hey');
system.debug(r1);


string abbbaa = ('Hamush');
m1.newMessage(abbbaa);
//m1.welcomeMessage();
//m1.samplePrintMessage('Hello hello');